packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  esbuild: true
  '@serialport/bindings-cpp': set this to true or false
  usb: set this to true or false
  better-sqlite3: true
